pub(crate) const WORD_LIST: &[&str] = &[
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "it",
    "for",
    "not",
    "on",
    "with",
    "he",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "an",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
    "when",
    "make",
    "can",
    "like",
    "time",
    "no",
    "just",
    "him",
    "know",
    "take",
    "people",
    "into",
    "year",
    "your",
    "good",
    "some",
    "could",
    "them",
    "see",
    "other",
    "than",
    "then",
    "now",
    "look",
    "only",
    "come",
    "its",
    "over",
    "think",
    "also",
    "back",
    "after",
    "use",
    "two",
    "how",
    "our",
    "work",
    "first",
    "well",
    "way",
    "even",
    "new",
    "want",
    "because",
    "any",
    "these",
    "give",
    "day",
    "most",
    "us",
    "great",
    "between",
    "need",
    "large",
    "often",
    "hand",
    "high",
    "place",
    "hold",
    "turn",
    "been",
    "here",
    "why",
    "ask",
    "went",
    "men",
    "read",
    "land",
    "different",
    "home",
    "move",
    "try",
    "kind",
    "picture",
    "again",
    "change",
    "off",
    "play",
    "spell",
    "air",
    "away",
    "animal",
    "house",
    "point",
    "page",
    "letter",
    "mother",
    "answer",
    "found",
    "study",
    "still",
    "learn",
    "plant",
    "cover",
    "food",
    "sun",
    "four",
    "state",
    "keep",
    "eye",
    "never",
    "last",
    "let",
    "thought",
    "city",
    "tree",
    "cross",
    "farm",
    "hard",
    "start",
    "might",
    "story",
    "saw",
    "far",
    "sea",
    "draw",
    "left",
    "late",
    "run",
    "while",
    "press",
    "close",
    "night",
    "real",
    "life",
    "few",
    "open",
    "seem",
    "together",
    "next",
    "white",
    "children",
    "begin",
    "got",
    "walk",
    "example",
    "ease",
    "paper",
];

pub(crate) const CONTRACTIONS: &[(&str, &[&str])] = &[
    ("are", &["aren't"]),
    ("can", &["can't"]),
    ("could", &["couldn't"]),
    ("did", &["didn't"]),
    ("does", &["doesn't"]),
    ("do", &["don't"]),
    ("have", &["haven't"]),
    ("is", &["isn't"]),
    ("it", &["it's", "it'll"]),
    ("you", &["you'll", "you're", "you've", "you'd"]),
    ("that", &["that's", "that'll", "that'd"]),
    ("there", &["there's", "there'll", "there'd"]),
    ("he", &["he's", "he'll", "he'd"]),
    ("she", &["she's", "she'll", "she'd"]),
    ("we", &["we're", "we'll", "we'd"]),
    ("they", &["they're", "they'll", "they'd"]),
    ("will", &["won't"]),
    ("would", &["wouldn't", "would've"]),
];
